obs_dict = listobs(vis='3c391_ctm_mosaic_10s_spw0.ms')
plotants(vis='3c391_ctm_mosaic_10s_spw0.ms',figfile='plotants_3c391_antenna_layout.png')
clearstat() # This removes the table lock generated by plotants in script mode
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms', flagbackup=True, mode='manual', scan='1')
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms', flagbackup=True, mode='manual', antenna='ea13,ea15')
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms', mode='quack', quackinterval=10.0, quackmode='beg')
clearstat() # This removes any existing table locks generated by flagdata
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms', selectdata=True, correlation='RR,LL', averagedata=True, avgchannel='64', coloraxis='field')
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='',correlation='RR,LL',
       timerange='',antenna='ea01',spw='0:31',
       xaxis='time',yaxis='antenna2',
       plotrange=[-1,-1,0,26],coloraxis='field')
gencal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.antpos',caltype='antpos')
setjy(vis='3c391_ctm_mosaic_10s_spw0.ms', listmodels=True)
setjy(vis='3c391_ctm_mosaic_10s_spw0.ms',field='J1331+3030',standard='Perley-Butler 2017',
      model='3C286_C.im',usescratch=True,scalebychan=True,spw='')
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms', caltable='3c391_ctm_mosaic_10s_spw0.G0all',
        field='0,1,9', refant='ea21', spw='0:27~36',
        gaintype='G',calmode='p', solint='int',
        minsnr=5, gaintable=['3c391_ctm_mosaic_10s_spw0.antpos'])
plotms(vis='3c391_ctm_mosaic_10s_spw0.G0all',xaxis='time',yaxis='phase',
        coloraxis='corr',iteraxis='antenna',plotrange=[-1,-1,-180,180])
flagdata(vis='3c391_ctm_mosaic_10s_spw0.ms',
         flagbackup=True, mode='manual', antenna='ea05')
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms', caltable='3c391_ctm_mosaic_10s_spw0.G0',
        field='J1331+3030', refant='ea21', spw='0:27~36', calmode='p', solint='int',
        minsnr=5, gaintable=['3c391_ctm_mosaic_10s_spw0.antpos'])
plotms(vis='3c391_ctm_mosaic_10s_spw0.G0',
        xaxis='time',yaxis='phase',coloraxis='corr',field='J1331+3030',iteraxis='antenna',
        plotrange=[-1,-1,-180,180],timerange='08:02:00~08:17:00')
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.K0',
        field='J1331+3030',refant='ea21',spw='0:5~58',gaintype='K',
        solint='inf',combine='scan',minsnr=5,
        gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                   '3c391_ctm_mosaic_10s_spw0.G0'])
plotms(vis='3c391_ctm_mosaic_10s_spw0.K0',xaxis='antenna1',yaxis='delay',coloraxis='baseline')
bandpass(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.B0',
         field='J1331+3030',spw='',refant='ea21',combine='scan',
         solint='inf',bandtype='B',
         gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                    '3c391_ctm_mosaic_10s_spw0.G0',
                    '3c391_ctm_mosaic_10s_spw0.K0'])
plotms(vis='3c391_ctm_mosaic_10s_spw0.B0',field='J1331+3030',
        xaxis='chan',yaxis='amp',coloraxis='corr',
        iteraxis='antenna',gridrows=2,gridcols=2)
plotms(vis='3c391_ctm_mosaic_10s_spw0.B0',field='J1331+3030',
        xaxis='chan',yaxis='phase',coloraxis='corr',plotrange=[-1,-1,-180,180],
        iteraxis='antenna',gridrows=2,gridcols=2)
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.G1',
        field='J1331+3030',spw='0:5~58',
        solint='inf',refant='ea21',gaintype='G',calmode='ap',solnorm=False,
        gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                   '3c391_ctm_mosaic_10s_spw0.K0',
                   '3c391_ctm_mosaic_10s_spw0.B0'],
                   interp=['','','nearest'])
gaincal(vis='3c391_ctm_mosaic_10s_spw0.ms',caltable='3c391_ctm_mosaic_10s_spw0.G1',
        field='J1822-0938',
        spw='0:5~58',solint='inf',refant='ea21',gaintype='G',calmode='ap',
        gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                   '3c391_ctm_mosaic_10s_spw0.K0',
                   '3c391_ctm_mosaic_10s_spw0.B0'],
        append=True)
plotms(vis='3c391_ctm_mosaic_10s_spw0.G1',xaxis='time',yaxis='phase',
       gridrows=1,gridcols=2,iteraxis='corr',coloraxis='baseline',
       plotrange=[-1,-1,-180,180],plotfile='plotms_3c391-G1-phase.png')
plotms(vis='3c391_ctm_mosaic_10s_spw0.G1',xaxis='time',yaxis='amp',
       gridrows=1,gridcols=2,iteraxis='corr',coloraxis='baseline',
       plotfile='plotms_3c391-G1-amp.png')
plotms(vis='3c391_ctm_mosaic_10s_spw0.G1', xaxis='time', yaxis='phase',
        correlation='/', coloraxis='baseline', plotrange=[-1,-1,-180,180])
myscale = fluxscale(vis='3c391_ctm_mosaic_10s_spw0.ms',
                    caltable='3c391_ctm_mosaic_10s_spw0.G1',
                    fluxtable='3c391_ctm_mosaic_10s_spw0.fluxscale1',
                    reference='J1331+3030',
                    transfer=['J1822-0938'],
                    incremental=False)
plotms(vis='3c391_ctm_mosaic_10s_spw0.fluxscale1',xaxis='time',yaxis='amp',
       correlation='R',coloraxis='baseline')
plotms(vis='3c391_ctm_mosaic_10s_spw0.fluxscale1',xaxis='time',yaxis='amp',
       correlation='L',coloraxis='baseline')
applycal(vis='3c391_ctm_mosaic_10s_spw0.ms',
         field='J1331+3030',
         gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                    '3c391_ctm_mosaic_10s_spw0.fluxscale1',
                    '3c391_ctm_mosaic_10s_spw0.K0',
                    '3c391_ctm_mosaic_10s_spw0.B0'],
         gainfield=['','J1331+3030','',''],
         interp=['','nearest','',''],
         calwt=False)
applycal(vis='3c391_ctm_mosaic_10s_spw0.ms',
         field='J1822-0938',
         gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                    '3c391_ctm_mosaic_10s_spw0.fluxscale1',
                    '3c391_ctm_mosaic_10s_spw0.K0',
                    '3c391_ctm_mosaic_10s_spw0.B0'],
         gainfield=['','J1822-0938','',''],
         interp=['','nearest','',''],
         calwt=False)
applycal(vis='3c391_ctm_mosaic_10s_spw0.ms',
         field='2~8',
         gaintable=['3c391_ctm_mosaic_10s_spw0.antpos',
                    '3c391_ctm_mosaic_10s_spw0.fluxscale1',
                    '3c391_ctm_mosaic_10s_spw0.K0',
                    '3c391_ctm_mosaic_10s_spw0.B0'],
         gainfield=['','J1822-0938','',''],
         interp=['','linear','',''],
         calwt=False)
plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='0',correlation='RR,LL',
       antenna='',avgtime='60',xaxis='channel',yaxis='amp',
       ydatacolumn='corrected',coloraxis='corr',
       plotfile='plotms_3c391-fld0-corrected-amp.png')

plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='0',correlation='RR,LL',
       antenna='',avgtime='60',xaxis='channel',yaxis='phase',
       ydatacolumn='corrected',coloraxis='corr',
       plotrange=[-1,-1,-180,180],
       plotfile='plotms_3c391-fld0-corrected-phase.png')

plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='1',correlation='RR,LL',
       antenna='',avgtime='60',xaxis='channel',yaxis='amp',
       ydatacolumn='corrected',coloraxis='corr',
       plotfile='plotms_3c391-fld1-corrected-amp.png')

plotms(vis='3c391_ctm_mosaic_10s_spw0.ms',field='1',correlation='RR,LL',
       antenna='',avgtime='60',xaxis='channel',yaxis='phase',
       ydatacolumn='corrected',coloraxis='corr',
       plotrange=[-1,-1,-180,180],
       plotfile='plotms_3c391-fld1-corrected-phase.png')
split(vis='3c391_ctm_mosaic_10s_spw0.ms',outputvis='3c391_ctm_calib_spw0.ms',
      datacolumn='corrected',field='2~8',correlation='RR,LL')
statwt(vis='3c391_ctm_calib_spw0.ms',datacolumn='data')

tclean(vis='3c391_ctm_calib_spw0.ms', imagename='3C_391_image',
       field='', spw='', specmode='mfs', deconvolver='hogbom', nterms=1,
       gridder='mosaic', imsize=[480,480], cell=['2.5arcsec','2.5arcsec'],
       scales=[0, 5, 15, 45], smallscalebias=0.9,
       weighting='briggs', threshold='0mJy', niter=5000,
       interactive=False, savemodel='modelcolumn')

#convert to fits
exportfits(imagename='3C_391_image.image', fitsimage='3c391_casa.fits', velocity=False, optical=False, bitpix=-32, minpix=0, maxpix=-1, overwrite=False, dropstokes=False, stokeslast=True, history=True, dropdeg=False)
